apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-config
    namespace: staging
data:
    krakend.json: |
        {
            "version": 2,
            "extra_config": {
                "github_com/devopsfaith/krakend-cors": {
                    "allow_credentials": false,
                    "allow_headers": [ "Accept-Language" ],
                    "allow_methods": [ "GET", "HEAD" ],
                    "allow_origins": [ "*" ],
                    "debug": false,
                    "expose_headers": [
                        "Content-Length",
                        "Content-Type"
                    ],
                    "max_age": "1h"
                }
            },
            "endpoints": [
            ]
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway
    namespace: staging
spec:
    selector:
        matchLabels:
            app: gateway
    replicas: 1
    template:
        metadata:
            labels:
                app: gateway
        spec:
            volumes:
            -   name: gateway-volume
                configMap:
                    name: gateway-config
            containers:
            -   name: gateway
                image: devopsfaith/krakend:1.4.1-alpine
                ports:
                -   containerPort: 8080
                resources:
                    limits:
                        cpu: "0.2m"
                        memory: "256Mi"
                    requests:
                        cpu: "0.1m"
                        memory: "128Mi"
                volumeMounts:
                -   name: gateway-volume
                    mountPath: /etc/krakend/krakend.json
                    subPath: krakend.json
---
apiVersion: v1
kind: Service
metadata:
    name: gateway-service
    namespace: staging
spec:
    type: NodePort
    selector:
        app: gateway
    ports:
      -   port: 8080
          nodePort: 30080
