apiVersion: v1
kind: ConfigMap
metadata:
    name: server-healthcheck-config
    namespace: staging
data:
    krakend.json: |
        {
            "version": 2,
            "extra_config": {
                "github_com/devopsfaith/krakend-cors": {
                    "allow_credentials": false,
                    "allow_headers": ["Accept-Language"],
                    "allow_methods": ["GET", "HEAD"],
                    "allow_origins": ["*"],
                    "debug": false,
                    "expose_headers": [
                        "Content-Length",
                        "Content-Type"
                    ],
                    "max_age": "1h"
                }
            },
            "endpoints": [{
                "endpoint": "/health",
                "backend": [{
                    "host": ["http://localhost:8080"],
                    "url_pattern": "/__health"
                }],
                "extra_config": {
                    "github.com/devopsfaith/krakend/proxy": {
                        "static": {
                            "strategy": "always",
                            "data": {
                                "hello": "world"
                            }
                        }
                    }
                }
            }]
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-healthcheck
    namespace: staging
spec:
    selector:
        matchLabels:
            app: server-healthcheck
    replicas: 1
    template:
        metadata:
            labels:
                app: server-healthcheck
        spec:
            volumes:
            -   name: server-healthcheck-volume
                configMap:
                    name: server-healthcheck-config
            containers:
            -   name: server-healthcheck
                image: devopsfaith/krakend:1.4.1-alpine
                ports:
                -   containerPort: 8080
                resources:
                    limits:
                        cpu: "0.2m"
                        memory: "256Mi"
                    requests:
                        cpu: "0.1m"
                        memory: "128Mi"
                volumeMounts:
                -   name: server-healthcheck-volume
                    mountPath: /etc/krakend/krakend.json
                    subPath: krakend.json
---
apiVersion: v1
kind: Service
metadata:
    name: server-healthcheck-service
    namespace: staging
spec:
    type: NodePort
    selector:
        app: server-healthcheck
    ports:
      -   port: 8080
          nodePort: 30080
