apiVersion: v1
kind: ConfigMap
metadata:
    name: marvin-gateway-config
    namespace: staging
data:
    krakend.json: |
        {
            "version": 3,
            "extra_config": {
                "github_com/devopsfaith/krakend-cors": {
                    "allow_credentials": false,
                    "allow_headers": ["Accept-Language"],
                    "allow_methods": ["GET", "HEAD"],
                    "allow_origins": ["*"],
                    "debug": false,
                    "expose_headers": [
                        "Content-Length",
                        "Content-Type"
                    ],
                    "max_age": "1h"
                }
            },
            "endpoints": [
                {
                    "endpoint": "/music/ping",
                    "backend": [{
                        "url_pattern": "/ping",
                        "host": [ "marvin-music-nginx" ]
                    }]
                }, {
                    "endpoint": "/music/stats",
                    "output_encoding": "no-op",
                    "input_query_strings": [
                        "date"
                    ],
                    "backend": [{
                        "encoding": "no-op",
                        "url_pattern": "/stats",
                        "host": [ "marvin-music-nginx" ]
                    }]
                }
            ]
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: marvin-gateway
    namespace: staging
spec:
    selector:
        matchLabels:
            app: marvin-gateway
    replicas: 1
    template:
        metadata:
            labels:
                app: marvin-gateway
        spec:
            volumes:
            -   name: marvin-gateway-volume
                configMap:
                    name: marvin-gateway-config
            containers:
            -   name: marvin-gateway
                image: devopsfaith/krakend:2.0
                ports:
                -   containerPort: 8080
                resources:
                    limits:
                        cpu: "1m"
                        memory: "128Mi"
                volumeMounts:
                -   name: marvin-gateway-volume
                    mountPath: /etc/krakend/krakend.json
                    subPath: krakend.json
---
apiVersion: v1
kind: Service
metadata:
    name: marvin-gateway
    namespace: staging
spec:
    type: NodePort
    selector:
        app: marvin-gateway
    ports:
        -   port: 8080
            nodePort: 30090
