apiVersion: v1
kind: Service
metadata:
    name: marvin-music-nginx
    namespace: staging
spec:
    selector:
        app: marvin-music
    ports:
        -   port: 80
            targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: marvin-music-php
    namespace: staging
spec:
    selector:
        app: marvin-music
    ports:
        -   port: 9000
            targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: marvin-music
    namespace: staging
spec:
    selector:
        matchLabels:
            app: marvin-music
    replicas: 1
    template:
        metadata:
            labels:
                app: marvin-music
        spec:
            # Portainer's internal alias for GitHub registry
            imagePullSecrets:
            -   name: registry-1
            containers:
            -   name: nginx
                image: ghcr.io/marvinisaac/nginx-api/nginx-api:v1.0.3
                ports:
                -   containerPort: 80
                resources:
                    limits:
                        cpu: "100m"
                        memory: "128Mi"
                env:
                    -   name: PHP_HOSTNAME
                        value: marvin-music-php
                    -   name: VIRTUAL_HOST
                        value: _
            -   name: php
                image: ghcr.io/marvinisaac/marvinisaac-music/marvinisaac-music:v0.1.1
                ports:
                -   containerPort: 9000
                resources:
                    limits:
                        cpu: "1"
                        memory: "128Mi"
                env:
                    -   name: APP_DEBUG
                        value: "0"
                    -   name: APP_ENV
                        value: prod
                    -   name: APP_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: marvin-music-secret
                                key: APP_SECRET

                    -   name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: marvin-music-secret
                                key: DATABASE_URL

                    -   name: SPOTIFY_ENCODED_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: marvin-music-secret
                                key: SPOTIFY_ENCODED_SECRET
                    -   name: SPOTIFY_REFRESH_TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: marvin-music-secret
                                key: SPOTIFY_REFRESH_TOKEN
